import asyncio
import re
import subprocess
import sys
from pathlib import Path

import typer
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from .bench import BenchMetrics, load_corpus, metrics_to_row, run_benchmark
from .config import Settings
from .db import create_engine_and_sessionmaker
from .gate import Gate, GateExecutionError
from .models import BenchmarkResult, Decision, Finding, Severity
from .reviewer import PROMPT_VERSION, LLMError, Reviewer, ReviewFinding

app = typer.Typer(help="agentdiff tooling")

SEVERITY_ORDER = {
    Severity.NIT: 0,
    Severity.MINOR: 1,
    Severity.MAJOR: 2,
    Severity.BLOCKER: 3,
}

SEVERITY_COLORS = {
    Severity.BLOCKER: "31",
    Severity.MAJOR: "33",
    Severity.MINOR: "36",
    Severity.NIT: "2",
}

_ANSI = re.compile(r"\x1b\[[0-9;]*m")


def _paint(text: str, code: str) -> str:
    if not sys.stdout.isatty():
        return text
    return f"\033[{code}m{text}\033[0m"


def _strip(text: str) -> str:
    return _ANSI.sub("", text)


def format_plain_table(headers: list[str], rows: list[list[str]]) -> str:
    widths = [len(h) for h in headers]
    for row in rows:
        for index, cell in enumerate(row):
            widths[index] = max(widths[index], len(_strip(cell)))
    lines = ["  ".join(h.ljust(w) for h, w in zip(headers, widths))]
    lines.append("  ".join("-" * w for w in widths))
    for row in rows:
        lines.append("  ".join(c.ljust(widths[i] + len(c) - len(_strip(c))) for i, c in enumerate(row)))
    return "\n".join(lines)


def _config_column(row: BenchmarkResult) -> str:
    return f"{row.model_id}@{row.prompt_version}@{row.effort}"


def _ranked_rows(rows: list[BenchmarkResult]) -> list[BenchmarkResult]:
    return sorted(rows, key=lambda r: (-(r.f1 or 0.0), r.created_at))


def format_table(rows: list[BenchmarkResult]) -> str:
    headers = [
        "config",
        "TP",
        "FP",
        "FN",
        "precision",
        "recall",
        "f1",
        "mean_latency_ms",
        "mean_cost_usd",
        "clean_fp_rate",
        "cases",
        "clean_cases",
    ]
    width = [len(h) for h in headers]
    lines: list[list[str]] = []
    for row in _ranked_rows(rows):
        values = [
            _config_column(row),
            str(row.true_positives),
            str(row.false_positives),
            str(row.false_negatives),
            f"{row.precision:.3f}",
            f"{row.recall:.3f}",
            f"{row.f1:.3f}",
            f"{row.mean_latency_ms:.1f}",
            f"{row.mean_cost_usd or 0:.6f}",
            f"{row.clean_false_positive_rate:.3f}",
            str(row.total_cases),
            str(row.clean_cases),
        ]
        lines.append(values)
        width = [max(w, len(v)) for w, v in zip(width, values)]
    border = "-+-".join("-" * w for w in width)
    header_line = " | ".join(h.ljust(w) for h, w in zip(headers, width))
    body = [
        " | ".join(v.ljust(w) for v, w in zip(values, width)) for values in lines
    ]
    return "\n".join([header_line, border, *body])


def results_markdown(rows: list[BenchmarkResult]) -> str:
    headers = [
        "config",
        "TP",
        "FP",
        "FN",
        "precision",
        "recall",
        "f1",
        "mean_latency_ms",
        "mean_cost_usd",
        "clean_fp_rate",
        "cases",
        "clean_cases",
    ]
    lines = [
        "# agentdiff benchmark scoreboard\n",
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("---" for _ in headers) + "|",
    ]
    for row in _ranked_rows(rows):
        values = [
            _config_column(row),
            str(row.true_positives),
            str(row.false_positives),
            str(row.false_negatives),
            f"{row.precision:.3f}",
            f"{row.recall:.3f}",
            f"{row.f1:.3f}",
            f"{row.mean_latency_ms:.1f}",
            f"{row.mean_cost_usd or 0:.6f}",
            f"{row.clean_false_positive_rate:.3f}",
            str(row.total_cases),
            str(row.clean_cases),
        ]
        lines.append("| " + " | ".join(values) + " |")
    lines.append(
        "\nGenerated by `python -m agentdiff bench`. Numbers reflect the corpus in "
        "`bench/corpus/`; a low score is a finding, not a bug.\n"
    )
    return "\n".join(lines)


async def _bench(
    *,
    model: str,
    effort: str,
    prompt_version: str,
    corpus_dir: Path,
    results_file: Path,
    settings: Settings | None = None,
    reviewer: Reviewer | None = None,
    session_factory: async_sessionmaker[AsyncSession] | None = None,
) -> BenchMetrics:
    settings = settings or Settings()
    reviewer = reviewer or Reviewer(settings)
    cases = load_corpus(corpus_dir)
    metrics = await run_benchmark(cases, reviewer, model, prompt_version, effort)

    engine = None
    if session_factory is None:
        engine, session_factory = create_engine_and_sessionmaker(settings.database_url)
    async with session_factory() as session:
        session.add(metrics_to_row(metrics))
        await session.commit()
        stmt = select(BenchmarkResult).order_by(BenchmarkResult.created_at.desc())
        rows = list((await session.execute(stmt)).scalars().all())
    if engine is not None:
        await engine.dispose()

    typer.echo(format_table(rows))
    results_file.parent.mkdir(parents=True, exist_ok=True)
    results_file.write_text(results_markdown(rows) + "\n")
    return metrics


@app.command()
def bench(
    model: str = typer.Option("claude-opus-5", "--model"),
    effort: str = typer.Option("high", "--effort"),
    prompt_version: str = typer.Option(PROMPT_VERSION, "--prompt-version"),
    corpus: Path = typer.Option(Path("bench/corpus"), "--corpus"),
    results_file: Path = typer.Option(Path("bench/RESULTS.md"), "--results-file"),
) -> None:
    """Run the corpus against the reviewer, persist the score, print the scoreboard."""
    asyncio.run(
        _bench(
            model=model,
            effort=effort,
            prompt_version=prompt_version,
            corpus_dir=corpus,
            results_file=results_file,
        )
    )


def _git_diff(repo: Path, base: str, head: str) -> str:
    result = subprocess.run(
        ["git", "diff", base, head],
        cwd=repo,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        typer.echo(f"git diff failed: {result.stderr.strip()}", err=True)
        raise typer.Exit(code=1)
    return result.stdout


def _finding_row(finding: ReviewFinding) -> list[str]:
    location = finding.file_path
    if finding.start_line is not None:
        location += f":{finding.start_line}"
        if finding.end_line is not None and finding.end_line != finding.start_line:
            location += f"-{finding.end_line}"
    return [
        _paint(finding.severity.value, SEVERITY_COLORS[finding.severity]),
        finding.category.value,
        location,
        finding.title,
        f"{finding.confidence:.2f}",
    ]


async def _review(
    base: str,
    head: str,
    repo: Path,
    json_output: bool,
    settings: Settings | None = None,
    reviewer: Reviewer | None = None,
) -> None:
    settings = settings or Settings()
    reviewer = reviewer or Reviewer(settings)
    diff = _git_diff(repo, base, head)
    try:
        outcome = await reviewer.review(diff=diff)
    except LLMError as exc:
        typer.echo(f"review failed: {exc}", err=True)
        raise typer.Exit(code=1)
    if json_output:
        typer.echo(outcome.result.model_dump_json(indent=2))
        return
    if not outcome.result.findings:
        typer.echo("No findings.")
        return
    rows = [
        _finding_row(f)
        for f in sorted(
            outcome.result.findings,
            key=lambda f: -SEVERITY_ORDER[f.severity],
        )
    ]
    typer.echo(
        format_plain_table(
            ["SEVERITY", "CATEGORY", "LOCATION", "TITLE", "CONF"], rows
        )
    )
    typer.echo(
        f"tokens in/out/cache_read: {outcome.input_tokens}/{outcome.output_tokens}/"
        f"{outcome.cache_read_tokens}  cost_usd={outcome.cost_usd}  "
        f"latency_ms={outcome.latency_ms}"
    )


@app.command()
def review(
    base: str = typer.Option(..., "--base", help="Base SHA or ref"),
    head: str = typer.Option(..., "--head", help="Head SHA or ref"),
    repo: Path = typer.Option(Path("."), "--repo"),
    json_output: bool = typer.Option(False, "--json", help="Print raw JSON"),
) -> None:
    """Review the diff between two SHAs and print the findings."""
    asyncio.run(_review(base=base, head=head, repo=repo, json_output=json_output))


async def _gate(
    base: str,
    head: str,
    repo: Path,
    fail_on: str,
    settings: Settings | None = None,
    reviewer: Reviewer | None = None,
) -> int:
    settings = settings or Settings(workspace_dir=repo)
    reviewer = reviewer or Reviewer(settings)
    threshold = Severity(fail_on)
    diff = _git_diff(repo, base, head)
    try:
        outcome = await reviewer.review(diff=diff)
    except LLMError as exc:
        typer.echo(f"review failed: {exc}", err=True)
        return 1
    findings = [
        Finding(
            file_path=f.file_path,
            start_line=f.start_line,
            end_line=f.end_line,
            severity=f.severity,
            category=f.category,
            title=f.title,
            rationale=f.rationale,
            suggested_patch=f.suggested_patch,
            confidence=f.confidence,
        )
        for f in outcome.result.findings
    ]
    try:
        pairs = await Gate(settings, reviewer).gate_all(findings, head)
    except GateExecutionError as exc:
        typer.echo(f"gate failed: {exc}", err=True)
        return 1

    rows: list[list[str]] = []
    failing: list[Finding] = []
    for finding, decision in pairs:
        rows.append(
            [
                _paint(finding.severity.value, SEVERITY_COLORS[finding.severity]),
                _paint(decision.decision.value, "32" if decision.decision == Decision.ACCEPTED else "31"),
                decision.reason.value,
                decision.verification or "-",
                finding.file_path,
                finding.title,
            ]
        )
        if (
            decision.decision == Decision.ACCEPTED
            and SEVERITY_ORDER[finding.severity] >= SEVERITY_ORDER[threshold]
        ):
            failing.append(finding)

    typer.echo(
        format_plain_table(
            ["SEVERITY", "DECISION", "REASON", "VERIFIED", "LOCATION", "TITLE"],
            rows,
        )
    )
    accepted = sum(1 for _, d in pairs if d.decision == Decision.ACCEPTED)
    rejected = len(pairs) - accepted
    typer.echo(f"accepted={accepted} rejected={rejected} fail_on={fail_on}")
    if failing:
        typer.echo(
            f"FAIL: {len(failing)} accepted finding(s) at or above {fail_on} severity",
            err=True,
        )
        return 1
    return 0


@app.command()
def gate(
    base: str = typer.Option(..., "--base", help="Base SHA or ref"),
    head: str = typer.Option(..., "--head", help="Head SHA or ref"),
    repo: Path = typer.Option(Path("."), "--repo"),
    fail_on: str = typer.Option("major", "--fail-on", help="blocker|major|minor"),
) -> None:
    """Review the diff, gate every suggestion behind the test suite, fail on accepted findings."""
    code = asyncio.run(_gate(base=base, head=head, repo=repo, fail_on=fail_on))
    raise typer.Exit(code=code)


@app.command()
def serve(
    host: str = typer.Option("0.0.0.0", "--host"),
    port: int = typer.Option(8000, "--port"),
) -> None:
    """Run the API server."""
    import uvicorn

    uvicorn.run("agentdiff.main:app", host=host, port=port)
