import asyncio
from pathlib import Path

import typer
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from .bench import BenchMetrics, load_corpus, metrics_to_row, run_benchmark
from .config import Settings
from .db import create_engine_and_sessionmaker
from .models import BenchmarkResult
from .reviewer import PROMPT_VERSION, Reviewer

app = typer.Typer(help="agentdiff tooling")


def _config_column(row: BenchmarkResult) -> str:
    return f"{row.model_id}@{row.prompt_version}@{row.effort}"


def _ranked_rows(rows: list[BenchmarkResult]) -> list[BenchmarkResult]:
    return sorted(rows, key=lambda r: (-(r.f1 or 0.0), r.created_at))


def format_table(rows: list[BenchmarkResult]) -> str:
    headers = [
        "config",
        "TP",
        "FP",
        "FN",
        "precision",
        "recall",
        "f1",
        "mean_latency_ms",
        "mean_cost_usd",
        "clean_fp_rate",
        "cases",
        "clean_cases",
    ]
    width = [len(h) for h in headers]
    lines: list[list[str]] = []
    for row in _ranked_rows(rows):
        values = [
            _config_column(row),
            str(row.true_positives),
            str(row.false_positives),
            str(row.false_negatives),
            f"{row.precision:.3f}",
            f"{row.recall:.3f}",
            f"{row.f1:.3f}",
            f"{row.mean_latency_ms:.1f}",
            f"{row.mean_cost_usd or 0:.6f}",
            f"{row.clean_false_positive_rate:.3f}",
            str(row.total_cases),
            str(row.clean_cases),
        ]
        lines.append(values)
        width = [max(w, len(v)) for w, v in zip(width, values)]
    border = "-+-".join("-" * w for w in width)
    header_line = " | ".join(h.ljust(w) for h, w in zip(headers, width))
    body = [
        " | ".join(v.ljust(w) for v, w in zip(values, width)) for values in lines
    ]
    return "\n".join([header_line, border, *body])


def results_markdown(rows: list[BenchmarkResult]) -> str:
    headers = [
        "config",
        "TP",
        "FP",
        "FN",
        "precision",
        "recall",
        "f1",
        "mean_latency_ms",
        "mean_cost_usd",
        "clean_fp_rate",
        "cases",
        "clean_cases",
    ]
    lines = [
        "# agentdiff benchmark scoreboard\n",
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("---" for _ in headers) + "|",
    ]
    for row in _ranked_rows(rows):
        values = [
            _config_column(row),
            str(row.true_positives),
            str(row.false_positives),
            str(row.false_negatives),
            f"{row.precision:.3f}",
            f"{row.recall:.3f}",
            f"{row.f1:.3f}",
            f"{row.mean_latency_ms:.1f}",
            f"{row.mean_cost_usd or 0:.6f}",
            f"{row.clean_false_positive_rate:.3f}",
            str(row.total_cases),
            str(row.clean_cases),
        ]
        lines.append("| " + " | ".join(values) + " |")
    lines.append(
        "\nGenerated by `python -m agentdiff bench`. Numbers reflect the corpus in "
        "`bench/corpus/`; a low score is a finding, not a bug.\n"
    )
    return "\n".join(lines)


async def _bench(
    *,
    model: str,
    effort: str,
    prompt_version: str,
    corpus_dir: Path,
    results_file: Path,
    settings: Settings | None = None,
    reviewer: Reviewer | None = None,
    session_factory: async_sessionmaker[AsyncSession] | None = None,
) -> BenchMetrics:
    settings = settings or Settings()
    reviewer = reviewer or Reviewer(settings)
    cases = load_corpus(corpus_dir)
    metrics = await run_benchmark(cases, reviewer, model, prompt_version, effort)

    engine = None
    if session_factory is None:
        engine, session_factory = create_engine_and_sessionmaker(settings.database_url)
    async with session_factory() as session:
        session.add(metrics_to_row(metrics))
        await session.commit()
        stmt = select(BenchmarkResult).order_by(BenchmarkResult.created_at.desc())
        rows = list((await session.execute(stmt)).scalars().all())
    if engine is not None:
        await engine.dispose()

    typer.echo(format_table(rows))
    results_file.parent.mkdir(parents=True, exist_ok=True)
    results_file.write_text(results_markdown(rows) + "\n")
    return metrics


@app.command()
def bench(
    model: str = typer.Option("claude-opus-5", "--model"),
    effort: str = typer.Option("high", "--effort"),
    prompt_version: str = typer.Option(PROMPT_VERSION, "--prompt-version"),
    corpus: Path = typer.Option(Path("bench/corpus"), "--corpus"),
    results_file: Path = typer.Option(Path("bench/RESULTS.md"), "--results-file"),
) -> None:
    """Run the corpus against the reviewer, persist the score, print the scoreboard."""
    asyncio.run(
        _bench(
            model=model,
            effort=effort,
            prompt_version=prompt_version,
            corpus_dir=corpus,
            results_file=results_file,
        )
    )
